services:
  user-service:
    build:
      context: ./  # путь к папке с Dockerfile
    container_name: user-service
    ports:
      - "50053:50053"
    networks:
      - infra_net

networks:
  infra_net:
    external: true